name: lidarr

services:
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    ports:
      - ${PORT:-8686}:8686
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Toronto}
    volumes:
      - ${CONFIG_PATH}:/config
      - ${MUSIC_PATH}:/music
      - ${DOWNLOADS_PATH}:/downloads
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-1G}
