name: huntarr

services:
  huntarr:
    container_name: huntarr
    image: huntarr/huntarr:latest
    restart: always
    ports:
      - ${PORT:-9705}:9705
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      - ${CONFIG_PATH}:/config
