name: newt
services:
    newt:
        image: fosrl/newt:latest
        container_name: newt
        restart: unless-stopped
        environment:
            - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT}
            - NEWT_ID=${NEWT_ID}
            - NEWT_SECRET=${NEWT_SECRET}
